version: 0.0
os: linux
files:
 - source: .
   destination: /tramitapp_back
hooks:
  AfterInstall:
   - location: scripts/change_permissions.sh
   - location: scripts/install_app_dependencies.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: root
